### ISSUE TITLE
Healing Surge not being parsed properly for Resto Shaman

### ISSUE THREAD

**Issue by Nalhan** [MartijnHols/WoWAnalyzer#159] opened 2017-08-17 01:17 UTC
**What browser are you using?**
Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Link to an example report with the issue**
https://wowanalyzer.com/report/LaktPqpGrjcRAFTN/16-Heroic+Harjatan+-+Kill+(4:25)/Boating/cast-efficiency

**Expected behavior**
Healing Surge casts should be shown in the Cast Efficiency tab, but it registers 0 casts on a report where
I used 22. This causes the Unused Tidal Waves and the TW cast ratio metrics to be wrong because it doesn't know Healing Surge is being used. I've seen this on every report I've tried.

**Comment by Yuyz0112** [comment] 2017-08-17 02:42
I think this was a bug caused by recent commits because it works fine in my out-date code branch. I am going to look into how this was happened.

**Comment by Nighteyez07** [comment] 2017-08-17 19:33
This is fixed in this PR [https://github.com/MartijnHols/WoWAnalyzer/pull/161](https://github.com/MartijnHols/WoWAnalyzer/pull/161) . The issue is that Enhance and Resto both having the spell Healing Surge, but they are different Spell Ids. Updated the Spell Ids per spec and all the references used.

**Closed** 2017-08-17 23:01 UTC
