### ISSUE TITLE
Mistmeaver HPK UI Increasing

### ISSUE THREAD

**Issue by Groumph** [MartijnHols/WoWAnalyzer#68] opened 2017-06-04 04:16 UTC
**What browser are you using?**
Chrome Version 58.0.3029.110 (64-bit)

**Link to an example report with the issue**
https://www.warcraftlogs.com/reports/V7dB3jybzwQTYJAc

**Expected behavior**
Mistweaver HPK should be static when switch between options in the bottom menu. However currently it increases as I change option.
![mwhpk2](https://cloud.githubusercontent.com/assets/127517/26758886/e93e6fb0-48a9-11e7-8248-a3390bd23b40.PNG)
![mwhpk1](https://cloud.githubusercontent.com/assets/127517/26758888/e941c9da-48a9-11e7-9575-ba0d626af4d0.PNG)
![mwhpk3](https://cloud.githubusercontent.com/assets/127517/26758887/e940168a-48a9-11e7-907f-91d2fbe764b6.PNG)

**Comment by fasib** [comment] 2017-06-04 10:32
Looks like just clicking multiple times on `Suggestions` is enough to reproduce the error.

**Comment by anom0ly** [comment] 2017-06-04 13:17
Just pushed a fix that should prevent this issue from occurring in the future.

Thanks!

**Closed** 2017-06-04 14:00 UTC
